GET http://localhost:3000/user/1

###
GET http://localhost:3000/stundenplan/5BHITM/2022/23

###
GET http://localhost:3000/stundenplan/faecher

###
GET http://localhost:3000/verspaetungen/5BHITM?uhrzeit=11:30&tag=Montag

###
GET http://localhost:3000/verspaetungen/1
